import sys

z01_Request_Fields = {
    "Standard_Map_Data": {
        "Company_Identifier": 4,
        "Terminal_Class_ID": 1,
        "Terminal_Format_Level": 2,
        "Multiple_Inquiry_Flag": 1,
        "Response_Format_Code": 2,
        "Request_Format_Code": 2,
        "Transaction_Type": 2,
        "Sequence_Number": 6,
        "Date": 6,
        "Time": 4,
        "Terminal_Location_ID": 15,  # Named Terminal_ID in spec's map info
        "Company_ID": 4,
        "Unique_Device_ID": 4,
        "Account_Number": 0,  # Variable Length
        "Field_Sep_Track2": 1,
        "Exp_Date_Track2:": 4,
        "Disc_Data_Track2": 0,  # Variable_Length
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        "Terminal_Type": 1,
        "Authorization_Number:": 6,
    },
    "Detail_Information": {
        # "Track_1": 76,  # 76 is the max value
        "Track_2": 37,  # 37 is the max value
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Credit_Plan": 5,
        "Authorization_Number": 6,
        "Authorization_Type": 1,
        "Surcharge_Amount": 6,
        "Offered_Down_Payment": 7,
        "Tax_Amount": 6,
        "Chip_Condition_Code": 1,
        "PO_number": 15,
        "CVV2_Presence_Indicator": 1,
        "CVV2": 4,
        "Moto_Indicator": 1,
        "Settlement_Indicator": 1,
        "Filler": 1,
        "KSN": [0, 16, 20],
        "Encrypted_Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Terminal_Type": 1,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Authorisation_Response_Code": 2,
        "Reserved": [1, 4, 17, 20, 66],
        "Addendum_Presence_Indicator": 1,
        "Currency_Code": 3,
        "Goods_Sold": 1,
        "Card_Type": 4,
        "Customer_Code": 25,
        "Odometer": 6,
        "Driver_Number": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Prompt_Data": 43,
        "Purchase_Device_Seq_Num": 5,
        "Avail_Prod_Capable_Ind": 1,
        "Product_Code_Set": 2,
        "Unit_Measure_1": 1,
        "Product_Code_1": [2, 3],
        "Quantity_1": 7,
        "Amount_1": 7,
        "Unit_Measure_2": 1,
        "Product_Code_2": [2, 3],
        "Quantity_2": 7,
        "Amount_2": 7,
        "Unit_Measure_3": 1,
        "Product_Code_3": [2, 3],
        "Quantity_3": 7,
        "Amount_3": 7,
        "Unit_Measure_4": 1,
        "Product_Code_4": [2, 3],
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": [2, 3],
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": [2, 3],
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,

    },
    "Specific_Information": {
        "Terminal Type": 1,
        "Authorization_Number": 6,
        "Card_Type": 4,
        "Employee_ID": 8,
        "Shift_Number": 3,
        "Control_Number": 6,
        "Access_Code": 4,
        "Terminal_Reference_Number": 12,
        "Retrieval_Ref_Num": 12,
        "Term_Ref_Num": 12
    },
    "Terminal_Diagnostics": {
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
    },
    "End_Terminal_Diagnostics": {
        "Reserved": [18, 19, 26],
        "Folio_Area_Tag": 2,
        "Purchase_ID_Format_Code": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,  # Variable Length
        "Field_Separator": 1,
        "Variable_Data_Area_Tag": 2,

    },
    "Client_Discretionary_Data_Dict": {
        "Client_Discretionary_Data": 0,  # Variable Length Data
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "Addendum_Data_Length": {
        "Field_Separator": 1,
        "Addendum_Data_Length": 4,
        "Number Tag_IDs": 2,
        "Tag ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder": 0
    },
    "Disc_Data_Capture_Fields": {
        "Authorization_Disc_Data": 0,  # Variable Length
        "Capture_Field_Identifier": 1,
        "Terminal_Type": 1,
        "Capture_Sequence_Number": 6,
        "Capture_Total_Amount": 6,
        "Capture_Disc_Data": 0,  # Variable Length
        "Field_Separator": 1,
        "Field_Separator_Holder": 1
    },

}

z01_Request_Field = {
    "Standard_Map_Data": {
        "Company_Identifier": 4,
        "Terminal_Class_ID": 1,
        "Terminal_Format_Level": 2,
        "Multiple_Inquiry_Flag": 1,
        "Response_Format_Code": 2,
        "Request_Format_Code": 2,
        "Transaction_Type": 2,
        "Sequence_Number": 6,
        "Date": 6,
        "Time": 4,
        "Terminal_Location_ID": 15,  # Named Terminal_ID in spec's map info
        "Company_ID": 4,
        "Unique_Device_ID": 4,  # This is not always present
        "Account_Number": 0,  # Variable Length
        "Field_Sep_Track2": 1,
        "Exp_Date_Track2:": 4,
        "Disc_Data_Track2": 0,  # Variable_Length
    },
    "01_C2": {
        # In the stupid Z01 Spec this map has duplicated standard map with random twists?
        # This might need reword to use the standard map -Uniq Dev ID
        "Company_Identifier": 4,
        "Terminal_Class_ID": 1,
        "Terminal_Format_Level": 2,
        "Multiple_Inquiry_Flag": 1,
        "Response_Format_Code": 2,
        "Request_Format_Code": 2,
        "Transaction_Type": 2,
        "Sequence_Number": 6,
        "Date": 6,
        "Time": 4,
        "Terminal_ID": 15,  # Named Terminal_ID in spec's map info
        "Company_ID": 4,
        # Detail Information
        "Track_2_Data": 37,
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        # Specific Information
        "Terminal_Type": 1,
        "Card_Type": 4,
        "Employee_ID": 8,
        "Shift_Number": 3,
        "Control_Number": 6,
        "Access_Code": 4,
        "Term_Reference_Number": 12,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "01_D3": {
        # Starts with Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "KSN": 16,
        "Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "01_D4": {
        # Starts with standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "KSN": 16,
        "Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Terminal_Type": 1,
        "PoS_Data_Codes": 12,
        "Authorization_Response_Code": 2,
        "Reserved": 20,
        "Addendum_Presence_Ind": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum_Tag_Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "03_C1": {
        # Starts with standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        "Terminal_Type": 1,
        "Authorization_Number": 6,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "03_C2": {
        # Another weird ass map
        # Uses Standard map -Unique Dev ID
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        # Specific Information
        "Authorization_Number": 6,
        "Terminal_Type": 1,
        "Card_Type": 4,
        "Employee_ID": 8,
        "Shift_Number": 3,
        "Control_Number": 6,
        "Access_Code": 4,
        "Retrieval_Ref_Num": 12,
        "Term_Reference_Number": 12,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "03_D0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Reserved": 8,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    # Uses Standard Map
    "05_B2": {
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "CVV2_Indicator": 1,
        "CVV2": 4,
        "Moto_Indicator": 1,
        "Terminal_Type": 1,
        "Settlement_Indicator": 1,
        "Filler": 1,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Authorisation_Response_Code": 2,
        "Reserved": 4,
        "Goods_Sold": 1,
        "Reserved_2": 33,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # End of Term Diagnostics
        "Reserved_3": 19,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,  # Variable Length
        "Field Separator": 1,
        "Variable_Data_Area_Tag": 2,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "05_F0": {
        # Starts with standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Settlement_Indicator": 1,
        "Filler": 1,
        "Good_Sold": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # End of Terminal Diagnostics
        "Folio_Area_Tag": 2,
        "Purch_ID_Format_Code": 1,
        "Reserved": 26,
        "Field_Separator": 1,
        "Reserved_2": 18,
        "Field_Separator_2": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,  # Variable Length
        "Field Separator": 1,
        "Variable_Data_Area_Tag": 2,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator_3": 1,
        "Field_Separator_Holder": 1,
    },
    "05_F2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "CVV2_Indicator": 1,
        "CVV2": 4,
        "Moto_Indicator": 1,
        "Terminal_Type": 1,
        "Settlement_Indicator": 1,
        "Filler": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # End of Terminal Diagnostics
        "Folio_Area_Tag": 2,
        "Purch_ID_Format_Code": 1,
        "Reserved": 26,
        "Field_Separator": 1,
        "Reserved_2": 18,
        "Field_Separator_2": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,  # Variable Length
        "Field Separator": 1,
        "Variable_Data_Area_Tag": 2,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator_3": 1,
        "Field_Separator_Holder": 1,
    },
    "05_G2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Tax_Amount": 6,
        "Customer_Code": 25,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Authorisation_Response_Code": 2,
        "Reserved": 4,
        "Terminal_Type": 1,
        "Settlement_Indicator": 1,
        "Reserved_2": 32,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "05_NT": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Settlement_Indicator": 1,
        "Reserved": 2,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_NO": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_N2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Credit_Plan": 5,
        "Offered_Down_Payment": 7,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_N9": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Card_Type": 4,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_P0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Tax_Amount": 6,
        "Customer_Code": 25,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_P5": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_P6": {
        # Uses Standard Map
        # This map appears identical to the P5...?
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_P7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "PO_Number": 15,
        "Business_Date": 6,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "05_P8": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_Set": 2,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        "Authorisation_Response_Code": 2,
        "Settlement_Indicator": 1,
        "Reserved": 17,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "05_W7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Fuel_Service_Type": 2,
        "Prompt_Data": 43,
        "Vehicle_Card_Number": 5,
        "Addendum_Presence_Indicator": 1,
        "Available Products": 1,
        "Reserved": 1,
        "Unit_Measure": 1,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Unit_Measure_2": 1,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Unit_Measure_3": 1,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Unit_Measure_4": 1,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "11_B2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Surcharge_Amount": 6,
        "PoS_Data_Codes": 12,
        "Mobil_Device_Indicator": 1,
        "Reserved": 66,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "11_E3": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        "EBT_Type": 2,
        "Terminal_Type": 1,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Voucher_Number": 15,
        "Reserved": 10,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_G2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Tax_Code": 6,
        "Customer_Code": 25,
        "Surcharge_Amount": 6,
        "PoS_Data_Code": 12,
        "Mobile_Device_Indicator": 1,
        "Terminal_Type": 1,
        "Reserved": 65,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "11_N8": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_P0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Tax_Amount": 6,
        "Customer_Code": 25,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_P5": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_P6": {
        # Uses Standard Map
        # Again its the same as P5..?
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_P7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "PO_Number": 15,
        "Date": 6,
        "Invoice_Total": 12,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "11_P8": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_Set": 2,
        "Surcharge_Amount": 6,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Reserved": 1,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        "Reserved_2": 20,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "11_W7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Authorisation_Number": 6,
        "Authorization_Type": 1,
        "Terminal_Type": 1,
        "Fuel_Service_Type": 2,
        "Prompt_Data": 43,
        "Authorization_Amount": 7,
        "Purchase_Device_Seq_Number": 5,
        "Addendum_Presence_Indicator": 1,
        "Reserved": 2,
        "Unit_Measure": 1,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Unit_Measure_2": 1,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Unit_Measure_3": 1,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Unit_Measure_4": 1,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "13_B2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "CVV2_Indicator": 1,
        "CVV2": 4,
        "Moto_Indicator": 1,
        "Purchase_Type": 1,
        "Terminal_Type": 1,
        "Cash_Over_Amount": 6,
        "Surcharge_Amount": 6,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Goods_Sold": 1,
        "Reserved": 3,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,
        "Field_Separator": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator_2": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_3": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "13_C2": {
        # Weird Fucking Map
        # Uses Standard - Unique ID
        "Card_Use_Type": 1,
        "Total_Amount:": 7,
        "Currency_Code": 3,
        # Specific INformation
        "Terminal_Type": 1,
        "Sale_Type": 1,
        "Card_Type": 4,
        "Employee_ID": 8,
        "Shift_Number": 3,
        "Control_Number": 6,
        "Access_Code": 4,
        "Usage_Code": 1,
        "Terminal_Reference_Number": 12,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator_2": 1,
        "Field_Separator_Holder": 1,
    },
    "13_D3": {
        # Starts with Standard Map
        # Same as 01 version..?
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "KSN": 16,
        "Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_D4": {
        # Starts with standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "KSN": 16,
        "Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Terminal_Type": 1,
        "PoS_Data_Codes": 12,
        "Reserved": 21,
        "Addendum_Presence_Ind": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum_Tag_Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "13_E3": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        "EBT_Type": 2,
        "Terminal_Type": 1,
        "Purchase_Type": 1,
        "KSN": 16,
        "Pin_Block": 16,
        "Cash_Back_Amount": 6,
        "Convenience_Fee_Amount": 6,
        "Reserved": 25,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_F0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Mail_Indicator": 1,
        "Terminal_Type": 1,
        "Reserved": 2,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        "Folio_Area_Tag": 2,
        "Purchase_ID_Format_Code": 1,
        "Reserved_2": 39,
        "Field_Separator_2": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,
        "Field_Separator_3": 1,
        "Variable_Data_Area_Tag": 2,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_F2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "CVV2_Presence_Indicator": 1,
        "CVV2": 4,
        "Moto_Indicator": 1,
        "Purchase_Type": 1,
        "Terminal_Type": 1,
        "Filler": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        "Folio_Area_Tag": 2,
        "Purchase_ID_Format_Code": 1,
        "Reserved_2": 39,
        "Field_Separator_2": 1,
        "AVS_Area_Tag": 2,
        "AVS_Information": 0,
        "Field_Separator_3": 1,
        "Variable_Data_Area_Tag": 2,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_G2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Tax_Amount": 6,
        "Customer_Code": 25,
        "Surcharge_Amount": 6,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Reserved": 65,
        "Addendum_Presence_indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum_Tag_Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "13_N0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_N2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Credit_Plan": 5,
        "Offered_Down_Payment": 7,
        "Product_Code_1": 4,
        "Product_Code_2": 4,
        "Product_Code_3": 4,
        "Product_Code_4": 4,
        "Product_Code_5": 4,
        "Unused": 11,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_P0": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Tax_Code": 6,
        "Customer_Code": 25,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_P5": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_P6": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_P7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Odometer": 6,
        "Driver": 6,
        "PO_Number": 15,
        "Business_Date": 6,
        "Invoice_Total": 12,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    "13_P8": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Odometer": 6,
        "Driver": 6,
        "Control_Number": 4,
        "Vehicle_Number": 6,
        "Fuel_Measure": 1,
        "Fuel_Service_Type": 2,
        "Product_Code_Set": 2,
        "Surcharge_Amount": 6,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Chip_Condition_Code": 1,
        "Product_Code_1": 2,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Product_Code_2": 2,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Product_Code_3": 2,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Product_Code_4": 2,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Product_Code_5": 2,
        "Quantity_5": 7,
        "Amount_5": 7,
        "Product_Code_6": 2,
        "Quantity_6": 7,
        "Amount_6": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        "Reserved": 20,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum_Tag_Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "13_W7": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Terminal_Type": 1,
        "Fuel_Service_Type": 2,
        "Prompt_Data": 43,
        "Purchase_Device_Seq_Number": 5,
        "Addendum_Presence_Indicator": 1,
        "Reserved": 2,
        "Unit_Measure": 1,
        "Product_Code_1": 3,
        "Quantity_1": 7,
        "Amount_1": 7,
        "Unit_Measure_2": 1,
        "Product_Code_2": 3,
        "Quantity_2": 7,
        "Amount_2": 7,
        "Unit_Measure_3": 1,
        "Product_Code_3": 3,
        "Quantity_3": 7,
        "Amount_3": 7,
        "Unit_Measure_4": 1,
        "Product_Code_4": 3,
        "Quantity_4": 7,
        "Amount_4": 7,
        "Sales_Tax": 5,
        "Discount": 5,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "30_B2": {
        # Uses Standard Map
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "PoS_Data_Codes": 12,
        "Mobile_Device_Indicator": 1,
        "Reserved": 1,
        "Reversal_Reason": 1,
        "Reserved_2": 40,
        "Addendum_Presence_Indicator": 1,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
        # Addendum Tag Data
        "Field_Separator_2": 1,
        "Addendum_Data_Length": 4,
        "Number_Tag_IDs": 2,
        "Tag_ID": 3,
        "Tag_Data_Length": 4,
        "Tag_Data": 0,
        "Field_Separator_Holder_2": 1,
    },
    "30_C2": {
        # In the stupid Z01 Spec this map has duplicated standard map with random twists?
        # This might need reword to use the standard map -Uniq Dev ID
        "Company_Identifier": 4,
        "Terminal_Class_ID": 1,
        "Terminal_Format_Level": 2,
        "Multiple_Inquiry_Flag": 1,
        "Response_Format_Code": 2,
        "Request_Format_Code": 2,
        "Transaction_Type": 2,
        "Sequence_Number": 6,
        "Date": 6,
        "Time": 4,
        "Terminal_ID": 15,  # Named Terminal_ID in spec's map info
        "Company_ID": 4,
        # Detail Information
        "Track_2_Data": 37,
        "Card_Use_Type": 1,
        "Total_Amount": 7,
        "Currency_Code": 3,
        # Specific Information
        "Terminal_Type": 1,
        "Card_Type": 4,
        "Employee_ID": 8,
        "Shift_Number": 3,
        "Control_Number": 6,
        "Access_Code": 4,
        "Term_Reference_Number": 12,
        # Term Diagnostics
        "Number_Dial_Attempts": 1,
        "Terminal_Reason_Code": 2,
        "Host_Dialed": 1,
        # Client Disc Data
        "Client_Discretionary_Data": 0,
        "Field_Separator": 1,
        "Field_Separator_Holder": 1,
    },
    # Uses Standard Map
    "Card_Use_Type": 1,
    "Total_Amount": 7,
    "Currency_Code": 3,
    "EBT_Type": 2,
    "Cash_Back_Amount": 6,
    "Convenience_Fee_Amount": 6,
    "Reserved": 10,
    # Term Diagnostics
    "Number_Dial_Attempts": 1,
    "Terminal_Reason_Code": 2,
    "Host_Dialed": 1,
    # Client Disc Data
    "Client_Discretionary_Data": 0,
    "Field_Separator": 1,
    "Field_Separator_Holder": 1,

}

print("Enter string, press 'ctrl+d' when done to input")
user_Input = str(sys.stdin.readlines())  # Reads multi-line string input and assigns to variable
print(user_Input)
print("~-~-~-~-~-~-~")

user_Input = user_Input.split(",")
print(user_Input)

user_Input_Combined = ''
for user_Input_String in user_Input:
    user_Input_String = user_Input_String.partition("INF:      ")[2]
    user_Input_String = user_Input_String.partition("\\n'")[0]
    user_Input_String = user_Input_String.replace("'", "")
    user_Input_String = user_Input_String.replace("]", "")
    user_Input_Combined += user_Input_String + " "

user_Input_Combined = user_Input_Combined.replace("  ", " ")
user_Input_List = user_Input_Combined.split(" ")
print(user_Input_List)
